<?php
//echo 'hola';
//$contenido = '<!doctype html>';
//$contenido.= '<head>';
//$contenido.= 'enido';
//$contenido.= '<br>';
//$contenido.= 'enido';

//$contenido = '<!doctype html>'
//$contenido.= '<html xmlns="http://www.w3.org/1999/xhtml" xmlns:v="urn:schemas-microsoft-com:vml" xmlns:o="urn:schemas-microsoft-com:office:office">';
$contenido= '<head>';
$contenido.= '<meta charset="UTF-8">';
$contenido.= '<meta http-equiv="X-UA-Compatible" content="IE=edge">';
$contenido.= '<meta name="viewport" content="width=device-width, initial-scale=1">';
$contenido.= '<title>*|MC:SUBJECT|*</title>';
$contenido.= '<style type="text/css">';
$contenido.= 'p{';
$contenido.= 'margin:10px 0;';
$contenido.= 'padding:0;';
$contenido.= '}';
$contenido.= 'table{';
$contenido.= 'border-collapse:collapse;';
$contenido.= '}';
$contenido.= 'h1,h2,h3,h4,h5,h6{';
$contenido.= 'display:block;';
$contenido.= 'margin:0;';
$contenido.= 'padding:0;';
$contenido.= '}';
$contenido.= 'img,a img{';
$contenido.= 'border:0;';
$contenido.= 'height:auto;';
$contenido.= 'outline:none;';
$contenido.= 'text-decoration:none;';
$contenido.= '}';
$contenido.= 'body,#bodyTable,#bodyCell{';
$contenido.= 'height:100%;';
$contenido.= 'margin:0;';
$contenido.= 'padding:0;';
$contenido.= 'width:100%;';
$contenido.= '}';
$contenido.= '.mcnPreviewText{';
$contenido.= 'display:none !important;';
$contenido.= '}';
$contenido.= '#outlook a{';
$contenido.= 'padding:0;';
$contenido.= '}';
$contenido.= 'img{';
$contenido.= '-ms-interpolation-mode:bicubic;';
$contenido.= '}';
$contenido.= 'table{';
$contenido.= 'mso-table-lspace:0pt;';
$contenido.= 'mso-table-rspace:0pt;';
$contenido.= '}';
$contenido.= '.ReadMsgBody{';
$contenido.= 'width:100%;';
$contenido.= '}';
$contenido.= '.ExternalClass{';
$contenido.= 'width:100%;';
$contenido.= '}';
$contenido.= 'p,a,li,td,blockquote{';
$contenido.= 'mso-line-height-rule:exactly;';
$contenido.= '}';
$contenido.= 'a[href^=tel],a[href^=sms]{';
$contenido.= 'color:inherit;';
$contenido.= 'cursor:default;';
$contenido.= 'text-decoration:none;';
$contenido.= '}';
$contenido.= 'p,a,li,td,body,table,blockquote{';
$contenido.= '-ms-text-size-adjust:100%;';
$contenido.= '-webkit-text-size-adjust:100%;';
$contenido.= '}';
$contenido.= '.ExternalClass,.ExternalClass p,.ExternalClass td,.ExternalClass div,.ExternalClass span,.ExternalClass font{';
$contenido.= 'line-height:100%;';
$contenido.= '}';
$contenido.= 'a[x-apple-data-detectors]{';
$contenido.= 'color:inherit !important;';
$contenido.= 'text-decoration:none !important;';
$contenido.= 'font-size:inherit !important;';
$contenido.= 'font-family:inherit !important;';
$contenido.= 'font-weight:inherit !important;';
$contenido.= 'line-height:inherit !important;';
$contenido.= '}';
$contenido.= '#bodyCell{';
$contenido.= 'padding:10px;';
$contenido.= '}';
$contenido.= '.templateContainer{';
$contenido.= 'max-width:600px !important;';
$contenido.= '}';
$contenido.= 'a.mcnButton{';
$contenido.= 'display:block;';
$contenido.= '}';
$contenido.= '.mcnImage,.mcnRetinaImage{';
$contenido.= 'vertical-align:bottom;';
$contenido.= '}';
$contenido.= '.mcnTextContent{';
$contenido.= 'word-break:break-word;';
$contenido.= '}';
$contenido.= '.mcnTextContent img{';
$contenido.= 'height:auto !important;';
$contenido.= '}';
$contenido.= '.mcnDividerBlock{';
$contenido.= 'table-layout:fixed !important;';
$contenido.= '}';
$contenido.= 'body,#bodyTable{';
$contenido.= '/*@editable*/background-color:#FAFAFA;';
$contenido.= '}';
$contenido.= '#bodyCell{';
$contenido.= '/*@editable*/border-top:0;';
$contenido.= '}';
$contenido.= '.templateContainer{';
$contenido.= '/*@editable*/border:0;';
$contenido.= '}';
$contenido.= 'h1{';
$contenido.= '/*@editable*/color:#202020;';
$contenido.= '/*@editable*/font-family:Helvetica;';
$contenido.= '/*@editable*/font-size:26px;';
$contenido.= '/*@editable*/font-style:normal;';
$contenido.= '/*@editable*/font-weight:bold;';
$contenido.= '/*@editable*/line-height:125%;';
$contenido.= '/*@editable*/letter-spacing:normal;';
$contenido.= '/*@editable*/text-align:left;';
$contenido.= '}';
$contenido.= 'h2{';
$contenido.= '/*@editable*/color:#202020;';
$contenido.= '/*@editable*/font-family:Helvetica;';
$contenido.= '/*@editable*/font-size:22px;';
$contenido.= '/*@editable*/font-style:normal;';
$contenido.= '/*@editable*/font-weight:bold;';
$contenido.= '/*@editable*/line-height:125%;';
$contenido.= '/*@editable*/letter-spacing:normal;';
$contenido.= '/*@editable*/text-align:left;';
$contenido.= 'h3{';
$contenido.= '/*@editable*/color:#202020;';
$contenido.= '/*@editable*/font-family:Helvetica;';
$contenido.= '/*@editable*/font-size:20px;';
$contenido.= '/*@editable*/font-style:normal;';
$contenido.= '/*@editable*/font-weight:bold;';
$contenido.= '/*@editable*/line-height:125%;';
$contenido.= '/*@editable*/letter-spacing:normal;';
$contenido.= '/*@editable*/text-align:left;';
$contenido.= '}';
$contenido.= 'h4{';
$contenido.= '/*@editable*/color:#202020;';
$contenido.= '/*@editable*/font-family:Helvetica;';
$contenido.= '/*@editable*/font-size:18px;';
$contenido.= '/*@editable*/font-style:normal;';
$contenido.= '/*@editable*/font-weight:bold;';
$contenido.= '/*@editable*/line-height:125%;';
$contenido.= '/*@editable*/letter-spacing:normal;';
$contenido.= '/*@editable*/text-align:left;';
$contenido.= '}';
$contenido.= '#templatePreheader{';
$contenido.= '/*@editable*/background-color:#FAFAFA;';
$contenido.= '/*@editable*/background-image:none;';
$contenido.= '/*@editable*/background-repeat:no-repeat;';
$contenido.= '/*@editable*/background-position:center;';
$contenido.= '/*@editable*/background-size:cover;';
$contenido.= '/*@editable*/border-top:0;';
$contenido.= '/*@editable*/border-bottom:0;';
$contenido.= '/*@editable*/padding-top:9px;';
$contenido.= '/*@editable*/padding-bottom:9px;';
$contenido.= '}';
$contenido.= '#templatePreheader .mcnTextContent,#templatePreheader .mcnTextContent p{';
$contenido.= '/*@editable*/color:#656565;';
$contenido.= '/*@editable*/font-family:Helvetica;';
$contenido.= '/*@editable*/font-size:12px;';
$contenido.= '/*@editable*/line-height:150%;';
$contenido.= '/*@editable*/text-align:left;';
$contenido.= '}';
$contenido.= '#templatePreheader .mcnTextContent a,#templatePreheader .mcnTextContent p a{';
$contenido.= '/*@editable*/color:#656565;';
$contenido.= '/*@editable*/font-weight:normal;';
$contenido.= '/*@editable*/text-decoration:underline;';
$contenido.= '}';
$contenido.= '#templateHeader{';
$contenido.= '/*@editable*/background-color:#FFFFFF;';
$contenido.= '/*@editable*/background-image:none;';
$contenido.= '/*@editable*/background-repeat:no-repeat;';
$contenido.= '/*@editable*/background-position:center;';
$contenido.= '/*@editable*/background-size:cover;';
$contenido.= '/*@editable*/border-top:0;';
$contenido.= '/*@editable*/border-bottom:0;';
$contenido.= '/*@editable*/padding-top:9px;';
$contenido.= '/*@editable*/padding-bottom:0;';
$contenido.= '}';
$contenido.= '#templateHeader .mcnTextContent,#templateHeader .mcnTextContent p{';
$contenido.= '/*@editable*/color:#202020;';
$contenido.= '/*@editable*/font-family:Helvetica;';
$contenido.= '/*@editable*/font-size:16px;';
$contenido.= '/*@editable*/line-height:150%;';
$contenido.= '/*@editable*/text-align:left;';
$contenido.= '}';
$contenido.= '#templateHeader .mcnTextContent a,#templateHeader .mcnTextContent p a{';
$contenido.= '/*@editable*/color:#2BAADF;';
$contenido.= '/*@editable*/font-weight:normal;';
$contenido.= '/*@editable*/text-decoration:underline;';
$contenido.= '}';
$contenido.= '#templateBody{';
$contenido.= '/*@editable*/background-color:#FFFFFF;';
$contenido.= '/*@editable*/background-image:none;';
$contenido.= '/*@editable*/background-repeat:no-repeat;';
$contenido.= '/*@editable*/background-position:center;';
$contenido.= '/*@editable*/background-size:cover;';
$contenido.= '/*@editable*/border-top:0;';
$contenido.= '/*@editable*/border-bottom:2px solid #EAEAEA;';
$contenido.= '/*@editable*/padding-top:0;';
$contenido.= '/*@editable*/padding-bottom:9px;';
$contenido.= '}';
$contenido.= '#templateBody .mcnTextContent,#templateBody .mcnTextContent p{';
$contenido.= '/*@editable*/color:#202020;';
$contenido.= '/*@editable*/font-family:Helvetica;';
$contenido.= '/*@editable*/font-size:16px;';
$contenido.= '/*@editable*/line-height:150%;';
$contenido.= '/*@editable*/text-align:left;';
$contenido.= '}';
$contenido.= '#templateBody .mcnTextContent a,#templateBody .mcnTextContent p a{';
$contenido.= '/*@editable*/color:#2BAADF;';
$contenido.= '/*@editable*/font-weight:normal;';
$contenido.= '/*@editable*/text-decoration:underline;';
$contenido.= '}';
$contenido.= '#templateFooter{';
$contenido.= '/*@editable*/background-color:#FAFAFA;';
$contenido.= '/*@editable*/background-image:none;';
$contenido.= '/*@editable*/background-repeat:no-repeat;';
$contenido.= '/*@editable*/background-position:center;';
$contenido.= '/*@editable*/background-size:cover;';
$contenido.= '/*@editable*/border-top:0;';
$contenido.= '/*@editable*/border-bottom:0;';
$contenido.= '/*@editable*/padding-top:9px;';
$contenido.= '/*@editable*/padding-bottom:9px;';
$contenido.= '}';
$contenido.= '#templateFooter .mcnTextContent,#templateFooter .mcnTextContent p{';
$contenido.= '/*@editable*/color:#656565;';
$contenido.= '/*@editable*/font-family:Helvetica;';
$contenido.= '/*@editable*/font-size:12px;';
$contenido.= '/*@editable*/line-height:150%;';
$contenido.= '/*@editable*/text-align:center;';
$contenido.= '}';
$contenido.= '#templateFooter .mcnTextContent a,#templateFooter .mcnTextContent p a{';
$contenido.= '/*@editable*/color:#656565;';
$contenido.= '/*@editable*/font-weight:normal;';
$contenido.= '/*@editable*/text-decoration:underline;';
$contenido.= '}';
$contenido.= '@media only screen and (min-width:768px){';
$contenido.= '.templateContainer{';
$contenido.= 'width:600px !important;';
$contenido.= '}';
$contenido.= '';
$contenido.= '}	@media only screen and (max-width: 480px){';
$contenido.= 'body,table,td,p,a,li,blockquote{';
$contenido.= '-webkit-text-size-adjust:none !important;';
$contenido.= '}';
$contenido.= '';
$contenido.= '}	@media only screen and (max-width: 480px){';
$contenido.= 'body{';
$contenido.= 'width:100% !important;';
$contenido.= 'min-width:100% !important;';
$contenido.= '}';
$contenido.= '';
$contenido.= '}	@media only screen and (max-width: 480px){';
$contenido.= '#bodyCell{';
$contenido.= 'padding-top:10px !important;';
$contenido.= '}';
$contenido.= '';
$contenido.= '}	@media only screen and (max-width: 480px){';
$contenido.= '.mcnRetinaImage{';
$contenido.= 'max-width:100% !important;';
$contenido.= '}';
$contenido.= '';
$contenido.= '}	@media only screen and (max-width: 480px){';
$contenido.= '.mcnImage{';
$contenido.= 'width:100% !important;';
$contenido.= '}';
$contenido.= '';
$contenido.= '}	@media only screen and (max-width: 480px){';
$contenido.= '.mcnCartContainer,.mcnCaptionTopContent,.mcnRecContentContainer,.mcnCaptionBottomContent,.mcnTextContentContainer,.mcnBoxedTextContentContainer,.mcnImageGroupContentContainer,.mcnCaptionLeftTextContentContainer,.mcnCaptionRightTextContentContainer,.mcnCaptionLeftImageContentContainer,.mcnCaptionRightImageContentContainer,.mcnImageCardLeftTextContentContainer,.mcnImageCardRightTextContentContainer,.mcnImageCardLeftImageContentContainer,.mcnImageCardRightImageContentContainer{';
$contenido.= 'max-width:100% !important;';
$contenido.= 'width:100% !important;';
$contenido.= '}';
$contenido.= '';
$contenido.= '}	@media only screen and (max-width: 480px){';
$contenido.= '.mcnBoxedTextContentContainer{';
$contenido.= 'min-width:100% !important;';
$contenido.= '}';
$contenido.= '';
$contenido.= '}	@media only screen and (max-width: 480px){';
$contenido.= '.mcnImageGroupContent{';
$contenido.= 'padding:9px !important;';
$contenido.= '}';
$contenido.= '';
$contenido.= '}	@media only screen and (max-width: 480px){';
$contenido.= '.mcnCaptionLeftContentOuter .mcnTextContent,.mcnCaptionRightContentOuter .mcnTextContent{';
$contenido.= 'padding-top:9px !important;';
$contenido.= '}';
$contenido.= '';
$contenido.= '}	@media only screen and (max-width: 480px){';
$contenido.= '.mcnImageCardTopImageContent,.mcnCaptionBottomContent:last-child .mcnCaptionBottomImageContent,.mcnCaptionBlockInner .mcnCaptionTopContent:last-child .mcnTextContent{';
$contenido.= 'padding-top:18px !important;';
$contenido.= '}';
$contenido.= '';
$contenido.= '}	@media only screen and (max-width: 480px){';
$contenido.= '.mcnImageCardBottomImageContent{';
$contenido.= 'padding-bottom:9px !important;';
$contenido.= '}';
$contenido.= '';
$contenido.= '}	@media only screen and (max-width: 480px){';
$contenido.= '.mcnImageGroupBlockInner{';
$contenido.= 'padding-top:0 !important;';
$contenido.= 'padding-bottom:0 !important;';
$contenido.= '}';
$contenido.= '';
$contenido.= '}	@media only screen and (max-width: 480px){';
$contenido.= '.mcnImageGroupBlockOuter{';
$contenido.= 'padding-top:9px !important;';
$contenido.= 'padding-bottom:9px !important;';
$contenido.= '}';
$contenido.= '';
$contenido.= '}	@media only screen and (max-width: 480px){';
$contenido.= '.mcnTextContent,.mcnBoxedTextContentColumn{';
$contenido.= 'padding-right:18px !important;';
$contenido.= 'padding-left:18px !important;';
$contenido.= '}';
$contenido.= '';
$contenido.= '}	@media only screen and (max-width: 480px){';
$contenido.= '.mcnImageCardLeftImageContent,.mcnImageCardRightImageContent{';
$contenido.= 'padding-right:18px !important;';
$contenido.= 'padding-bottom:0 !important;';
$contenido.= 'padding-left:18px !important;';
$contenido.= '}';
$contenido.= '';
$contenido.= '}	@media only screen and (max-width: 480px){';
$contenido.= '.mcpreview-image-uploader{';
$contenido.= 'display:none !important;';
$contenido.= 'width:100% !important;';
$contenido.= '}';
$contenido.= '';
$contenido.= '}	@media only screen and (max-width: 480px){';
$contenido.= '/*';
$contenido.= '@tab Mobile Styles';
$contenido.= '@section Heading 1';
$contenido.= '@tip Make the first-level headings larger in size for better readability on small screens.';
$contenido.= '*/';
$contenido.= 'h1{';
$contenido.= '/*@editable*/font-size:22px !important;';
$contenido.= '/*@editable*/line-height:125% !important;';
$contenido.= '}';
$contenido.= '';
$contenido.= '}	@media only screen and (max-width: 480px){';
$contenido.= '/*';
$contenido.= '@tab Mobile Styles';
$contenido.= '@section Heading 2';
$contenido.= '@tip Make the second-level headings larger in size for better readability on small screens.';
$contenido.= '*/';
$contenido.= 'h2{';
$contenido.= '/*@editable*/font-size:20px !important;';
$contenido.= '/*@editable*/line-height:125% !important;';
$contenido.= '}';
$contenido.= '';
$contenido.= '}	@media only screen and (max-width: 480px){';
$contenido.= '/*';
$contenido.= '@tab Mobile Styles';
$contenido.= '@section Heading 3';
$contenido.= '@tip Make the third-level headings larger in size for better readability on small screens.';
$contenido.= '*/';
$contenido.= 'h3{';
$contenido.= '/*@editable*/font-size:18px !important;';
$contenido.= '/*@editable*/line-height:125% !important;';
$contenido.= '}';
$contenido.= '';
$contenido.= '}	@media only screen and (max-width: 480px){';
$contenido.= '/*';
$contenido.= '@tab Mobile Styles';
$contenido.= '@section Heading 4';
$contenido.= '@tip Make the fourth-level headings larger in size for better readability on small screens.';
$contenido.= '*/';
$contenido.= 'h4{';
$contenido.= '/*@editable*/font-size:16px !important;';
$contenido.= '/*@editable*/line-height:150% !important;';
$contenido.= '}';
$contenido.= '';
$contenido.= '}	@media only screen and (max-width: 480px){';
$contenido.= '/*';
$contenido.= '@tab Mobile Styles';
$contenido.= '@section Boxed Text';
$contenido.= '@tip Make the boxed text larger in size for better readability on small screens. We recommend a font size of at least 16px.';
$contenido.= '*/';
$contenido.= '.mcnBoxedTextContentContainer .mcnTextContent,.mcnBoxedTextContentContainer .mcnTextContent p{';
$contenido.= '/*@editable*/font-size:14px !important;';
$contenido.= '/*@editable*/line-height:150% !important;';
$contenido.= '}';
$contenido.= '';
$contenido.= '}	@media only screen and (max-width: 480px){';
$contenido.= '/*';
$contenido.= '@tab Mobile Styles';
$contenido.= '@section Preheader Visibility';
$contenido.= '@tip Set the visibility of the email\'s preheader on small screens. You can hide it to save space.';
$contenido.= '*/';
$contenido.= '#templatePreheader{';
$contenido.= '/*@editable*/display:block !important;';
$contenido.= '}';
$contenido.= '';
$contenido.= '}	@media only screen and (max-width: 480px){';
$contenido.= '/*';
$contenido.= '@tab Mobile Styles';
$contenido.= '@section Preheader Text';
$contenido.= '@tip Make the preheader text larger in size for better readability on small screens.';
$contenido.= '*/';
$contenido.= '#templatePreheader .mcnTextContent,#templatePreheader .mcnTextContent p{';
$contenido.= '/*@editable*/font-size:14px !important;';
$contenido.= '/*@editable*/line-height:150% !important;';
$contenido.= '}';
$contenido.= '';
$contenido.= '}	@media only screen and (max-width: 480px){';
$contenido.= '/*';
$contenido.= '@tab Mobile Styles';
$contenido.= '@section Header Text';
$contenido.= '@tip Make the header text larger in size for better readability on small screens.';
$contenido.= '*/';
$contenido.= '#templateHeader .mcnTextContent,#templateHeader .mcnTextContent p{';
$contenido.= '/*@editable*/font-size:16px !important;';
$contenido.= '/*@editable*/line-height:150% !important;';
$contenido.= '}';
$contenido.= '';
$contenido.= '}	@media only screen and (max-width: 480px){';
$contenido.= '/*';
$contenido.= '@tab Mobile Styles';
$contenido.= '@section Body Text';
$contenido.= '@tip Make the body text larger in size for better readability on small screens. We recommend a font size of at least 16px.';
$contenido.= '*/';
$contenido.= '#templateBody .mcnTextContent,#templateBody .mcnTextContent p{';
$contenido.= '/*@editable*/font-size:16px !important;';
$contenido.= '/*@editable*/line-height:150% !important;';
$contenido.= '}';
$contenido.= '';
$contenido.= '}	@media only screen and (max-width: 480px){';
$contenido.= '/*';
$contenido.= '@tab Mobile Styles';
$contenido.= '@section Footer Text';
$contenido.= '@tip Make the footer content text larger in size for better readability on small screens.';
$contenido.= '*/';
$contenido.= '#templateFooter .mcnTextContent,#templateFooter .mcnTextContent p{';
$contenido.= '/*@editable*/font-size:14px !important;';
$contenido.= '/*@editable*/line-height:150% !important;';
$contenido.= '}';
$contenido.= '';
$contenido.= '}</style></head>';
$contenido.= '<body>';
$contenido.= '<!--*|IF:MC_PREVIEW_TEXT|*-->';
$contenido.= '<!--[if !gte mso 9]><!----><span class="mcnPreviewText" style="display:none; font-size:0px; line-height:0px; max-height:0px; max-width:0px; opacity:0; overflow:hidden; visibility:hidden; mso-hide:all;">*|MC_PREVIEW_TEXT|*</span><!--<![endif]-->';
$contenido.= '<!--*|END:IF|*-->';
$contenido.= '<center>';
$contenido.= '<table align="center" border="0" cellpadding="0" cellspacing="0" height="100%" width="100%" id="bodyTable">';
$contenido.= '<tr>';
$contenido.= '<td align="center" valign="top" id="bodyCell">';
$contenido.= '<!-- BEGIN TEMPLATE // -->';
$contenido.= '<!--[if (gte mso 9)|(IE)]>';
$contenido.= '<table align="center" border="0" cellspacing="0" cellpadding="0" width="600" style="width:600px;">';
$contenido.= '<tr>';
$contenido.= '<td align="center" valign="top" width="600" style="width:600px;">';
$contenido.= '<![endif]-->';
$contenido.= '<table border="0" cellpadding="0" cellspacing="0" width="100%" class="templateContainer">';
$contenido.= '<tr>';
$contenido.= '<td valign="top" id="templatePreheader"></td>';
$contenido.= '</tr>';
$contenido.= '<tr>';
$contenido.= '<td valign="top" id="templateHeader"><table border="0" cellpadding="0" cellspacing="0" width="100%" class="mcnImageBlock" style="min-width:100%;">';
$contenido.= '<tbody class="mcnImageBlockOuter">';
$contenido.= '<tr>';
$contenido.= '<td valign="top" style="padding:9px" class="mcnImageBlockInner">';
$contenido.= '<table align="left" width="100%" border="0" cellpadding="0" cellspacing="0" class="mcnImageContentContainer" style="min-width:100%;">';
$contenido.= '<tbody><tr>';
$contenido.= '<td class="mcnImageContent" valign="top" style="padding-right: 9px; padding-left: 9px; padding-top: 0; padding-bottom: 0; text-align:center;">';
$contenido.= '';
$contenido.= '';
$contenido.= '<img align="center" alt="" src="https://gallery.mailchimp.com/86c398649b070b1ddfd7b99e9/_compresseds/01644f21-f642-4dbe-850f-98808d10b1d4.jpg" width="564" style="max-width:1951px; padding-bottom: 0; display: inline !important; vertical-align: bottom;" class="mcnImage">';
$contenido.= '';
$contenido.= '';
$contenido.= '</td>';
$contenido.= '</tr>';
$contenido.= '</tbody></table>';
$contenido.= '</td>';
$contenido.= '</tr>';
$contenido.= '</tbody>';
$contenido.= '</table><table border="0" cellpadding="0" cellspacing="0" width="100%" class="mcnTextBlock" style="min-width:100%;">';
$contenido.= '<tbody class="mcnTextBlockOuter">';
$contenido.= '<tr>';
$contenido.= '<td valign="top" class="mcnTextBlockInner" style="padding-top:9px;">';
$contenido.= '<!--[if mso]>';
$contenido.= '<table align="left" border="0" cellspacing="0" cellpadding="0" width="100%" style="width:100%;">';
$contenido.= '<tr>';
$contenido.= '<![endif]-->';
$contenido.= '';
$contenido.= '<!--[if mso]>';
$contenido.= '<td valign="top" width="600" style="width:600px;">';
$contenido.= '<![endif]-->';
$contenido.= '<table align="left" border="0" cellpadding="0" cellspacing="0" style="max-width:100%; min-width:100%;" width="100%" class="mcnTextContentContainer">';
$contenido.= '<tbody><tr>';
$contenido.= '';
$contenido.= '<td valign="top" class="mcnTextContent" style="padding-top:0; padding-right:18px; padding-bottom:9px; padding-left:18px;">';
$contenido.= '';
$contenido.= '<h1 style="text-align: center;"><span style="font-family:verdana,geneva,sans-serif">¡¡FELICITACIONES!!</span></h1>';
$contenido.= '';
$contenido.= '<div style="text-align: center;"><em><span style="color:#808080"><span style="font-family:verdana,geneva,sans-serif">Acabas de ayudar a reconstruir Torres Del Paine</span></span></em></div>';
$contenido.= '';
$contenido.= '<p style="text-align: center;"><span style="font-family:verdana,geneva,sans-serif">Con tu donación podremos reconstruir el sendero a Base Torres en el Parque Nacional Torres del Paine. Recuerda que el código para canjear tu M2 es el: XXXXX</span></p>';
$contenido.= '';
$contenido.= '<p style="text-align: center;"><span style="font-family:verdana,geneva,sans-serif">Pincha <strong><span style="color:#006400">AQUÍ </span></strong>para canjear tu código.</span><br>';
$contenido.= '<br>';
$contenido.= '<strong>¡Muchas gracias por Dejar Tu Huella!</strong></p>';
$contenido.= '';
$contenido.= '<p style="text-align: center;"><img data-file-id="336513" height="70" src="https://gallery.mailchimp.com/86c398649b070b1ddfd7b99e9/images/58e74223-75b8-4268-afbb-d85273bab857.png" style="border: 0px initial ; width: 150px; height: 70px; margin: 0px;" width="150"></p>';
$contenido.= '';
$contenido.= '</td>';
$contenido.= '</tr>';
$contenido.= '</tbody></table>';
$contenido.= '<!--[if mso]>';
$contenido.= '</td>';
$contenido.= '<![endif]-->';
$contenido.= '';
$contenido.= '<!--[if mso]>';
$contenido.= '</tr>';
$contenido.= '</table>';
$contenido.= '<![endif]-->';
$contenido.= '</td>';
$contenido.= '</tr>';
$contenido.= '</tbody>';
$contenido.= '</table><table border="0" cellpadding="0" cellspacing="0" width="100%" class="mcnImageBlock" style="min-width:100%;">';
$contenido.= '<tbody class="mcnImageBlockOuter">';
$contenido.= '<tr>';
$contenido.= '<td valign="top" style="padding:9px" class="mcnImageBlockInner">';
$contenido.= '<table align="left" width="100%" border="0" cellpadding="0" cellspacing="0" class="mcnImageContentContainer" style="min-width:100%;">';
$contenido.= '<tbody><tr>';
$contenido.= '<td class="mcnImageContent" valign="top" style="padding-right: 9px; padding-left: 9px; padding-top: 0; padding-bottom: 0; text-align:center;">';
$contenido.= '';
$contenido.= '';
$contenido.= '<img align="center" alt="" src="https://gallery.mailchimp.com/86c398649b070b1ddfd7b99e9/_compresseds/d7a57f64-b2a4-41ff-97bb-3aac01f5b7c9.jpg" width="564" style="max-width:1951px; padding-bottom: 0; display: inline !important; vertical-align: bottom;" class="mcnImage">';
$contenido.= '';
$contenido.= '';
$contenido.= '</td>';
$contenido.= '</tr>';
$contenido.= '</tbody></table>';
$contenido.= '</td>';
$contenido.= '</tr>';
$contenido.= '</tbody>';
$contenido.= '</table></td>';
$contenido.= '</tr>';
$contenido.= '<tr>';
$contenido.= '<td valign="top" id="templateBody"></td>';
$contenido.= '</tr>';
$contenido.= '<tr>';
$contenido.= '<td valign="top" id="templateFooter"><table border="0" cellpadding="0" cellspacing="0" width="100%" class="mcnBoxedTextBlock" style="min-width:100%;">';
$contenido.= '<!--[if gte mso 9]>';
$contenido.= '<table align="center" border="0" cellspacing="0" cellpadding="0" width="100%">';
$contenido.= '<![endif]-->';
$contenido.= '<tbody class="mcnBoxedTextBlockOuter">';
$contenido.= '<tr>';
$contenido.= '<td valign="top" class="mcnBoxedTextBlockInner">';
$contenido.= '';
$contenido.= '<!--[if gte mso 9]>';
$contenido.= '<td align="center" valign="top" ">';
$contenido.= '<![endif]-->';
$contenido.= '<table align="left" border="0" cellpadding="0" cellspacing="0" width="100%" style="min-width:100%;" class="mcnBoxedTextContentContainer">';
$contenido.= '<tbody><tr>';
$contenido.= '';
$contenido.= '<td style="padding-top:9px; padding-left:18px; padding-bottom:9px; padding-right:18px;">';
$contenido.= '';
$contenido.= '<table border="0" cellspacing="0" class="mcnTextContentContainer" width="100%" style="min-width: 100% !important;background-color: #007A41;">';
$contenido.= '<tbody><tr>';
$contenido.= '<td valign="top" class="mcnTextContent" style="padding: 18px;color: #F2F2F2;font-family: Helvetica;font-size: 14px;font-weight: normal;text-align: center;">';
$contenido.= '<span style="font-size:18px"><strong><span style="font-family:source sans pro,helvetica neue,helvetica,arial,sans-serif">Síguenos en nuestras redes sociales</span></strong></span>';
$contenido.= '</td>';
$contenido.= '</tr>';
$contenido.= '</tbody></table>';
$contenido.= '</td>';
$contenido.= '</tr>';
$contenido.= '</tbody></table>';
$contenido.= '<!--[if gte mso 9]>';
$contenido.= '</td>';
$contenido.= '<![endif]-->';
$contenido.= '';
$contenido.= '<!--[if gte mso 9]>';
$contenido.= '</tr>';
$contenido.= '</table>';
$contenido.= '<![endif]-->';
$contenido.= '</td>';
$contenido.= '</tr>';
$contenido.= '</tbody>';
$contenido.= '</table><table border="0" cellpadding="0" cellspacing="0" width="100%" class="mcnFollowBlock" style="min-width:100%;">';
$contenido.= '<tbody class="mcnFollowBlockOuter">';
$contenido.= '<tr>';
$contenido.= '<td align="center" valign="top" style="padding:9px" class="mcnFollowBlockInner">';
$contenido.= '<table border="0" cellpadding="0" cellspacing="0" width="100%" class="mcnFollowContentContainer" style="min-width:100%;">';
$contenido.= '<tbody><tr>';
$contenido.= '<td align="center" style="padding-left:9px;padding-right:9px;">';
$contenido.= '<table border="0" cellpadding="0" cellspacing="0" width="100%" style="min-width:100%;" class="mcnFollowContent">';
$contenido.= '<tbody><tr>';
$contenido.= '<td align="center" valign="top" style="padding-top:9px; padding-right:9px; padding-left:9px;">';
$contenido.= '<table align="center" border="0" cellpadding="0" cellspacing="0">';
$contenido.= '<tbody><tr>';
$contenido.= '<td align="center" valign="top">';
$contenido.= '<!--[if mso]>';
$contenido.= '<table align="center" border="0" cellspacing="0" cellpadding="0">';
$contenido.= '<tr>';
$contenido.= '<![endif]-->';
$contenido.= '';
$contenido.= '<!--[if mso]>';
$contenido.= '<td align="center" valign="top">';
$contenido.= '<![endif]-->';
$contenido.= '';
$contenido.= '<table align="left" border="0" cellpadding="0" cellspacing="0" class="mcnFollowStacked" style="display:inline;">';
$contenido.= '';
$contenido.= '<tbody><tr>';
$contenido.= '<td align="center" valign="top" class="mcnFollowIconContent" style="padding-right:10px; padding-bottom:9px;">';
$contenido.= '<a href="https://www.instagram.com/tumejorhuellaparaelpaine/" target="_blank"><img src="https://cdn-images.mailchimp.com/icons/social-block-v2/color-instagram-96.png" alt="Instagram" class="mcnFollowBlockIcon" width="48" style="width:48px; max-width:48px; display:block;"></a>';
$contenido.= '</td>';
$contenido.= '</tr>';
$contenido.= '';
$contenido.= '';
$contenido.= '</tbody></table>';
$contenido.= '';
$contenido.= '';
$contenido.= '<!--[if mso]>';
$contenido.= '</td>';
$contenido.= '<![endif]-->';
$contenido.= '';
$contenido.= '<!--[if mso]>';
$contenido.= '<td align="center" valign="top">';
$contenido.= '<![endif]-->';
$contenido.= '';
$contenido.= '<table align="left" border="0" cellpadding="0" cellspacing="0" class="mcnFollowStacked" style="display:inline;">';
$contenido.= '';
$contenido.= '<tbody><tr>';
$contenido.= '<td align="center" valign="top" class="mcnFollowIconContent" style="padding-right:10px; padding-bottom:9px;">';
$contenido.= '<a href="https://m.facebook.com/tumejorhuellaparaelpaine/" target="_blank"><img src="https://cdn-images.mailchimp.com/icons/social-block-v2/color-facebook-96.png" alt="Facebook" class="mcnFollowBlockIcon" width="48" style="width:48px; max-width:48px; display:block;"></a>';
$contenido.= '</td>';
$contenido.= '</tr>';
$contenido.= '';
$contenido.= '';
$contenido.= '</tbody></table>';
$contenido.= '';
$contenido.= '';
$contenido.= '<!--[if mso]>';
$contenido.= '</td>';
$contenido.= '<![endif]-->';
$contenido.= '';
$contenido.= '<!--[if mso]>';
$contenido.= '<td align="center" valign="top">';
$contenido.= '<![endif]-->';
$contenido.= '';
$contenido.= '<table align="left" border="0" cellpadding="0" cellspacing="0" class="mcnFollowStacked" style="display:inline;">';
$contenido.= '';
$contenido.= '<tbody><tr>';
$contenido.= '<td align="center" valign="top" class="mcnFollowIconContent" style="padding-right:0; padding-bottom:9px;">';
$contenido.= '<a href="http://www.tumejorhuella.com/home/" target="_blank"><img src="https://cdn-images.mailchimp.com/icons/social-block-v2/color-link-96.png" alt="Website" class="mcnFollowBlockIcon" width="48" style="width:48px; max-width:48px; display:block;"></a>';
$contenido.= '</td>';
$contenido.= '</tr>';
$contenido.= '';
$contenido.= '';
$contenido.= '</tbody></table>';
$contenido.= '';
$contenido.= '';
$contenido.= '<!--[if mso]>';
$contenido.= '</td>';
$contenido.= '<![endif]-->';
$contenido.= '';
$contenido.= '<!--[if mso]>';
$contenido.= '</tr>';
$contenido.= '</table>';
$contenido.= '<![endif]-->';
$contenido.= '</td>';
$contenido.= '</tr>';
$contenido.= '</tbody></table>';
$contenido.= '</td>';
$contenido.= '</tr>';
$contenido.= '</tbody></table>';
$contenido.= '</td>';
$contenido.= '</tr>';
$contenido.= '</tbody></table>';
$contenido.= '';
$contenido.= '</td>';
$contenido.= '</tr>';
$contenido.= '</tbody>';
$contenido.= '</table><table border="0" cellpadding="0" cellspacing="0" width="100%" class="mcnDividerBlock" style="min-width:100%;">';
$contenido.= '<tbody class="mcnDividerBlockOuter">';
$contenido.= '<tr>';
$contenido.= '<td class="mcnDividerBlockInner" style="min-width: 100%; padding: 10px 18px 25px;">';
$contenido.= '<table class="mcnDividerContent" border="0" cellpadding="0" cellspacing="0" width="100%" style="min-width: 100%;border-top: 2px solid #EEEEEE;">';
$contenido.= '<tbody><tr>';
$contenido.= '<td>';
$contenido.= '<span></span>';
$contenido.= '</td>';
$contenido.= '</tr>';
$contenido.= '</tbody></table>';
$contenido.= '<!--';
$contenido.= '<td class="mcnDividerBlockInner" style="padding: 18px;">';
$contenido.= '<hr class="mcnDividerContent" style="border-bottom-color:none; border-left-color:none; border-right-color:none; border-bottom-width:0; border-left-width:0; border-right-width:0; margin-top:0; margin-right:0; margin-bottom:0; margin-left:0;" />';
$contenido.= '-->';
$contenido.= '</td>';
$contenido.= '</tr>';
$contenido.= '</tbody>';
$contenido.= '</table><table border="0" cellpadding="0" cellspacing="0" width="100%" class="mcnTextBlock" style="min-width:100%;">';
$contenido.= '<tbody class="mcnTextBlockOuter">';
$contenido.= '<tr>';
$contenido.= '<td valign="top" class="mcnTextBlockInner" style="padding-top:9px;">';
$contenido.= '<!--[if mso]>';
$contenido.= '<table align="left" border="0" cellspacing="0" cellpadding="0" width="100%" style="width:100%;">';
$contenido.= '<tr>';
$contenido.= '<![endif]-->';
$contenido.= '';
$contenido.= '<!--[if mso]>';
$contenido.= '<td valign="top" width="600" style="width:600px;">';
$contenido.= '<![endif]-->';
$contenido.= '<table align="left" border="0" cellpadding="0" cellspacing="0" style="max-width:100%; min-width:100%;" width="100%" class="mcnTextContentContainer">';
$contenido.= '<tbody><tr>';
$contenido.= '';
$contenido.= '<td valign="top" class="mcnTextContent" style="padding-top:0; padding-right:18px; padding-bottom:9px; padding-left:18px;">';
$contenido.= '';
$contenido.= '<em>Copyright © 2018 Tu Mejor Huella, Todos los derechos reservados</em><br>';
$contenido.= 'deja@tumejorhuella.com*<br>';
$contenido.= '<br>';
$contenido.= '¿Cambiar preferencias?<br>';
$contenido.= 'Puedes&nbsp;<a href="*|UPDATE_PROFILE|*">Actualizar tus datos</a>&nbsp;o&nbsp;<a href="*|UNSUB|*" target="_blank">Anular suscripción</a><br>';
$contenido.= '<br>';
$contenido.= '¡Muchas gracias por contribuir en nuestra campaña! :)';
$contenido.= '</td>';
$contenido.= '</tr>';
$contenido.= '</tbody></table>';
$contenido.= '<!--[if mso]>';
$contenido.= '</td>';
$contenido.= '<![endif]-->';
$contenido.= '';
$contenido.= '<!--[if mso]>';
$contenido.= '</tr>';
$contenido.= '</table>';
$contenido.= '<![endif]-->';
$contenido.= '</td>';
$contenido.= '</tr>';
$contenido.= '</tbody>';
$contenido.= '</table></td>';
$contenido.= '</tr>';
$contenido.= '</table>';
$contenido.= '<!--[if (gte mso 9)|(IE)]>';
$contenido.= '</td>';
$contenido.= '</tr>';
$contenido.= '</table>';
$contenido.= '<![endif]-->';
$contenido.= '<!-- // END TEMPLATE -->';
$contenido.= '</td>';
$contenido.= '</tr>';
$contenido.= '</table>';
$contenido.= '</center>';
$contenido.= '</body>';
$contenido.= '</html>';

echo $contenido;

//		<meta charset="UTF-8">
//<meta http-equiv="X-UA-Compatible" content="IE=edge">

?>